LANGUAGES = {
    "id": {
        "welcome": "Selamat Datang di Aplikasi Surat Massal PMT",
        "login": "Silakan login untuk menggunakan aplikasi ini.",
        "username": "Username",
        "password": "Password",
        "login_button": "Login",
        "logout_button": "Logout",
        "dashboard_title": "Dashboard",
        "generate_title": "Generate Surat Massal",
        "choose_language": "Pilih Bahasa / Choose Language",
        "upload_template": "Upload Template Word (.docx) — Drag & Drop atau klik",
        "upload_data": "Upload Data Excel (.xlsx) — Drag & Drop atau klik",
        "select_name_col": "Pilih kolom Nama",
        "select_link_col": "Pilih kolom Link",
        "search_name": "Cari Nama (ketik untuk filter)",
        "select_name_preview": "Pilih Nama untuk Preview",
        "hide_preview": "Sembunyikan Preview",
        "show_preview": "Tampilkan Preview",
        "preview_letter": "📖 Pratinjau Surat (Visual dan Rapi)",
        "download_preview": "⬇️ Download Preview Surat",
        "generate_all": "Generate Semua Surat",
        "processing_letters": "Sedang memproses surat...",
        "generate_done": "✅ Proses generate selesai!",
        "download_all_zip": "Download Semua Surat (ZIP)",
        "view_log": "Lihat Log Generate",
        "logout_msg": "👋 Terima Kasih!",
        "logout_submsg": "Terima kasih telah menggunakan aplikasi ini.\n\n**See you!**",
        "back_login": "🔐 Kembali ke Halaman Login",
        "total_letters": "Total Surat Dibuat",
        "letters_success": "Surat Berhasil",
        "letters_failed": "Surat Gagal",
        "templates_available": "Template Tersedia",
        "last_data_rows": "Data Peserta Terakhir",
        "letters_success_vs_failed": "Statistik Surat Berhasil vs Gagal",
        "percentage_letters": "Persentase Surat",
        "last_activity": "Aktivitas Terakhir",
        "no_data": "Belum ada data surat untuk ditampilkan.",
        "no_activity": "Belum ada aktivitas generate surat.",
        "tips": "Tips Cepat",
        "tips_content": (
            "1. Upload template dan data Excel di halaman **Generate Surat**.\n"
            "2. Pilih kolom nama dan link sesuai data.\n"
            "3. Klik **Generate Semua Surat** dan tunggu hingga selesai.\n"
            "4. Unduh file ZIP berisi surat-surat yang sudah jadi."
        ),
        "app_version": "**Versi Aplikasi:** 1.0.0",
        "no_maintenance": "⚙️ *Tidak ada pemeliharaan sistem saat ini.*",
        "upload_first": "Silakan upload template dan data Excel terlebih dahulu.",
        "login_fail": "Username atau password salah.",
    },
    "en": {
        "welcome": "Welcome to PMT Bulk Letter Application",
        "login": "Please login to use this application.",
        "username": "Username",
        "password": "Password",
        "login_button": "Login",
        "logout_button": "Logout",
        "dashboard_title": "Dashboard",
        "generate_title": "Generate Bulk Letters",
        "choose_language": "Select Language / Pilih Bahasa",
        "upload_template": "Upload Word Template (.docx) — Drag & Drop or click",
        "upload_data": "Upload Excel Data (.xlsx) — Drag & Drop or click",
        "select_name_col": "Select Name Column",
        "select_link_col": "Select Link Column",
        "search_name": "Search Name (type to filter)",
        "select_name_preview": "Select Name for Preview",
        "hide_preview": "Hide Preview",
        "show_preview": "Show Preview",
        "preview_letter": "📖 Letter Preview (Visual and Neat)",
        "download_preview": "⬇️ Download Letter Preview",
        "generate_all": "Generate All Letters",
        "processing_letters": "Processing letters...",
        "generate_done": "✅ Generation process complete!",
        "download_all_zip": "Download All Letters (ZIP)",
        "view_log": "View Generation Log",
        "logout_msg": "👋 Thank You!",
        "logout_submsg": "Thank you for using this application.\n\n**See you!**",
        "back_login": "🔐 Back to Login Page",
        "total_letters": "Total Letters Created",
        "letters_success": "Successful Letters",
        "letters_failed": "Failed Letters",
        "templates_available": "Templates Available",
        "last_data_rows": "Last Data Rows",
        "letters_success_vs_failed": "Successful vs Failed Letters Statistics",
        "percentage_letters": "Letters Percentage",
        "last_activity": "Recent Activity",
        "no_data": "No letter data to display.",
        "no_activity": "No letter generation activity yet.",
        "tips": "Quick Tips",
        "tips_content": (
            "1. Upload template and Excel data in the **Generate Letters** page.\n"
            "2. Select name and link columns as per your data.\n"
            "3. Click **Generate All Letters** and wait until completion.\n"
            "4. Download the ZIP file containing generated letters."
        ),
        "app_version": "**App Version:** 1.0.0",
        "no_maintenance": "⚙️ *No system maintenance currently.*",
        "upload_first": "Please upload the template and Excel data first.",
        "login_fail": "Wrong username or password.",
    },
}

def t(key, lang="id"):
    return LANGUAGES.get(lang, LANGUAGES["id"]).get(key, key)